export const assets = {
  logoGoogle: "/logo_google.jpeg",
  logoMedicine: "/log_Medicine_03.png",
  logoFacebook: "/logo_facebook.jpg",
  logoMoMo: "/MoMo_Logo.png",
  logo_vnpay: "/logo_vnpay.png",
  logo_youtube: "/logo_youtube.png",
  cart_icon: "/cart_icon.png",
  profile_icon: "/profile_icon.png",
  search_icon: "/search_icon.png",
  stethoscope: "/stethoscope-disCa.svg",
  start_icon: "/star_icon.png",
  exchange_icon: "/exchange_icon.png",
  quality_icon: "/quality_icon.png",
  support_img: "/support_img.png",
};
