import type { Metadata } from "next";
import { Urbanist, Open_Sans } from "next/font/google";
import "../styles/globals.css";
import { cn } from "@/lib/utils";
import QueryProvider from "@/providers/query-provider";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { Toaster } from "@/components/ui/sonner";
import { ChatBox } from "@/components/chat/chat-box";
export const metadata: Metadata = {
  title: "MediGo",
  description: "Generated by create next app",
};
const urbanist = Urbanist({ subsets: ["latin"] });
const open_sans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open_sans",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("bg-background", open_sans.variable, urbanist.className)}
      >
        <QueryProvider>
          <Header />
          <main className="min-h-screen">
            <div className="container mx-auto px-4">
              <div className="flex flex-wrap gap-4">
                <section className="w-full">{children}</section>
              </div>
            </div>
          </main>

          {/* <ChatBox userId="user-demo-123" /> */}
          <ChatBox />

          <Footer />
          <Toaster richColors position="top-right" />
        </QueryProvider>
      </body>
    </html>
  );
}
